l_german:
  action_dynasty_member_can_be_invited: "[recipient.GetShortUINameNoTooltip] kann an den Hof eingeladen werden"
  action_dynasty_member_can_be_invited_label: "$action_dynasty_member_can_be_invited$"
  action_dynasty_member_can_be_invited_desc: "Dein [actor.Custom2('RelationToMe', recipient)] [recipient.GetShortUIName] möchte an euren Hof ziehen."
  action_dynasty_member_can_be_invited_click: "#I Klicken um sie an euren Hof einzuladen#!"
  action_dynasty_member_can_be_invited_combined_group_name: "Dynastie Mitglieder können eingeladen werden"
  action_dynasty_member_can_be_invited_combined_group_label: "Dynastie Mitglieder können eingeladen werden"
  action_dynasty_member_can_be_invited_combined_group_description: "Einige eurer [dynasty|E] Mitglieder möchten an euren Hof ziehen."
  action_dynasty_member_can_be_invited_combined_label: "Euer [actor.Custom2('RelationToMe', recipient)], [recipient.GetShortUINameNoTooltip]"
  action_dynasty_member_can_be_invited_combined_unimportant: "$action_dynasty_member_can_be_invited_unimportant$"
  action_dynasty_member_can_be_invited_unimportant: "@warning_icon!#X Ihr solltet euch zunächst auf etwas anderes konzentrieren"
  action_dynasty_member_can_marry: "[recipient.GetShortUINameNoTooltip] kann heiraten"
  action_dynasty_member_can_marry_label: "$action_dynasty_member_can_marry$"
  action_dynasty_member_can_marry_desc: "Ihr [actor.Custom2('RelationToMe', recipient)] [recipient.GetShortUIName] ist berechtigt zu heiraten.\n\n#help Eine passende [marriage|E] für [recipient.GetHerHim] zu arrangieren würde eurer [dynasty|E] helfen und kann sogar zu einer neuen [alliance|E] führen.#!"
  action_dynasty_member_can_marry_click: "#I Klicken um eine geeignete [spouse|E] zu finden#!"
  action_dynasty_member_can_marry_combined_group_name: "Dynastie Mitglieder können verheiratet werden"
  action_dynasty_member_can_marry_combined_group_label: "Dynastie Mitglieder können verheiratet werden"
  action_dynasty_member_can_marry_combined_group_description: "Einige eurer [dynasty|E] Mitglieder sind berechtigt zu heiraten.\n\n#help [marriages|E] für sie zu arrangieren würde eurer [dynasty|E] nützen und kann zu neuen [alliances|E] führen.#!"
  action_dynasty_member_can_marry_combined_label: "Euer [actor.Custom2('RelationToMe', recipient)], [recipient.GetShortUINameNoTooltip]"
  action_dynasty_member_can_marry_combined_unimportant: "$action_dynasty_member_can_marry_unimportant$"
  action_dynasty_member_can_marry_unimportant: "@warning_icon!#X Du solltest dich auf die Heirat deiner ältesten Kinder konzentrieren"
  action_can_assign_guardian_to_dynasty_kid: "Vormund kann zugewiesen werden"
  action_can_assign_guardian_to_dynasty_kid_combined_group_label: "Dynastie Kinder haben keinen Vormund"
  action_can_assign_guardian_to_dynasty_kid_combined_group_name: "$action_can_assign_guardian_to_dynasty_kid$"
  action_can_assign_guardian_to_dynasty_kid_desc: "Du kannst einen [guardian|E] für [recipient.GetShortUIName] bestimmen.$action_can_assign_guardian_to_dynasty_kid_HELP$"
  action_can_assign_guardian_to_dynasty_kid_combined_group_description: "Du kannst einen [guardians|E] für deine Kinder bestimmen.$action_can_assign_guardian_to_dynasty_kid_HELP$"
  action_can_assign_guardian_to_dynasty_kid_label: "Du kannst einen Vormunde für [recipient.GetShortUINameNoTooltip] bestimmen"
  action_can_assign_guardian_to_dynasty_kid_combined_label: "Euer [actor.Custom2('RelationToMe', recipient)], [recipient.GetShortUINameNoTooltip]"
  action_can_assign_guardian_to_dynasty_kid_click: "#I Klicken um einen [guardian|E] für [recipient.GetHerHim] zu bestimmen#!"
  action_can_assign_guardian_to_dynasty_kid_combined_unimportant: "@warning_icon!#X Nur deinen jüngeren Kindern fehlt [guardians|E]#!"
  action_can_assign_guardian_to_dynasty_kid_unimportant: "@warning_icon!#X Du hast viele ältere Kinder#!"
  action_can_assign_guardian_to_dynasty_kid_HELP: "\n\n#help deinen Kindern kann ein Vormund zugewiesen werden, der ihre [skills|E] und andere Kenntnisse an das Kind überträgt. Ein Vormund mit einem guten [education_trait|E] überträgt ihn an das Kind, während die Erziehung deines Kindes durch einen [vassal|E] dessen [opinion|E] von dir erhöht. Wenn du mehr Kontrolle möchtest, kannst du das Kind selbst erziehen. #!"
  action_can_set_education_focus_to_dynasty_kid: "Kind benötigt einen [education_focus|E]"
  action_can_set_education_focus_to_dynasty_kid_label: "[recipient.GetShortUINameNoTooltip] benötigt einen Bildungsschwerpunkt"
  action_can_set_education_focus_to_dynasty_kid_desc: "Du kannst einen [education_focus|E] für [recipient.GetShortUIName] wählen.\n\n$FOCUS_BELOW_MIN_AGE$"
  action_can_set_education_focus_to_dynasty_kid_combined_group_label: "Dynastie Kinder brauchen Bildungsschwerpunkte"
  action_can_set_education_focus_to_dynasty_kid_combined_group_name: "Kinder benötigen einen [education_focus|E]."
  action_can_set_education_focus_to_dynasty_kid_combined_group_description: "Du kannst [education_focus|E] für Kinder deiner Dynastie auswählen."
  action_can_set_education_focus_to_dynasty_kid_combined_label: "Euer [actor.Custom2('RelationToMe', recipient)], [recipient.GetShortUINameNoTooltip]"
  action_can_set_education_focus_to_dynasty_kid_click: "#I Klicken um einen [education_focus|E] für [recipient.GetHerHim] zu wählen#!"
  action_dynasty_member_can_be_landed: "[recipient.GetShortUINameNoTooltip] können Titel zugewiesen werden"
  action_dynasty_member_can_be_landed_label: "$action_dynasty_member_can_be_landed$"
  action_dynasty_member_can_be_landed_desc: "Euer [actor.Custom2('RelationToMe', recipient)] [recipient.GetShortUIName] möchte unwichtige Titel für [recipient.GetHerselfHimself]."
  action_dynasty_member_can_be_landed_click: "#I Klicken um ihnen Titel zu gewähren#!"
  action_dynasty_member_can_be_landed_combined_group_name: "Dynasty Mitglieder können Titel erhalten"
  action_dynasty_member_can_be_landed_combined_group_label: "Dynasty Mitglieder können Titel erhalten"
  action_dynasty_member_can_be_landed_combined_group_description: "Einige deiner [Dynastie|E] Mitglieder wollen Titel."
  action_dynasty_member_can_be_landed_combined_label: "Euer [actor.Custom2('RelationToMe', recipient)], [recipient.GetShortUINameNoTooltip]"
  action_dynasty_member_can_be_landed_combined_unimportant: "$action_dynasty_member_can_be_landed_unimportant$"
  action_dynasty_member_can_be_landed_unimportant: "@warning_icon!#X Du solltest dich zuerst auf jemand anderen konzentrieren"
  action_spread_witchcraft_in_your_house: "[recipient.GetShortUINameNoTooltip] kann eine Hexe werden"
  action_spread_witchcraft_in_your_house_label: "$action_spread_witchcraft_in_your_house$"
  action_spread_witchcraft_in_your_house_desc: "Euer [actor.Custom2('RelationToMe', recipient)] [recipient.GetShortUIName] ist neugierig auf Eure geheimen Praktiken, Ihr könnt [recipient.GetHerHim] über die Wege des Gehörnten Gottes unterrichten."
  action_spread_witchcraft_in_your_house_combined_group_label: "Mitglieder des Haushalts können zu Hexen werden"
  action_spread_witchcraft_in_your_house_combined_group_name: "$action_spread_witchcraft_in_your_house_combined_group_label$"
  action_spread_witchcraft_in_your_house_combined_group_description: "Mehrere Mitglieder deines [house|E] können davon überzeugt werden, den Gehörnten Gott anzubeten."
  action_spread_witchcraft_in_your_house_combined_label: "Ihr [actor.Custom2('RelationToMe', recipient)], [recipient.GetShortUINameNoTooltip]"
  action_spread_witchcraft_in_your_house_click: "#I Klicken Sie, um ein [Schema|E]# zu starten!"

  action_marry_off_courtiers: "[recipient.GetShortUINameNoTooltip] kann heiraten"
  action_marry_off_courtiers_label: "$action_marry_off_courtiers$"
  action_marry_off_courtiers_desc: "Ihr [actor.Custom2('RelationToMe', recipient)] [recipient.GetShortUIName] ist für eine Heirat geeignet.\n\n#help Eine passende [marriage|E] für [recipient.GetHerHim] zu arrangieren, könnte Ihrem [court|E] zugute kommen.#!"
  action_marry_off_courtiers_click: "#I Klicken Sie, um einen geeigneten [spouse|E] zu finden#!"
  action_marry_off_courtiers_combined_label: "[recipient.GetRelationToString( GetPlayer )], [recipient.GetShortUINameNoTooltip]"
  action_marry_off_courtiers_combined_group_name: "Ihre Höflinge können heiraten"
  action_marry_off_courtiers_combined_group_label: "$action_marry_off_courtiers_combined_group_name$"
  action_marry_off_courtiers_combined_group_description: "Mehrere Eurer [courtier|E]s haben die Möglichkeit, verheiratet zu werden.\n\n#help Für sie [marriages|E] zu arrangieren, könnte Eurem [courtier|E] zugute kommen.#!"

  action_convert_courtiers: "[recipient.GetShortUINameNoTooltip] kann bekehrt werden"
  action_convert_courtiers_label: "$action_convert_courtiers$"
  action_convert_courtiers_desc: "Dein [actor.Custom2('RelationToMe', Empfänger)] [recipient.GetShortUIName] kann zum [actor.GetFaith.GetName|V] bekehrt werden"
  action_convert_courtiers_click: "#Klicken, um Bekehrung zu verlangen#!"
  action_convert_courtiers_combined_label: "[recipient.GetRelationToString( GetPlayer )], [recipient.GetShortUINameNoTooltip]"
  action_convert_courtiers_combined_group_name: "Eure Höflinge können bekehrt werden"
  action_convert_courtiers_combined_group_label: "$action_convert_courtiers_combined_group_name$"
  action_convert_courtiers_combined_group_description: "Mehrere Eurer Höflinge können zu [actor.GetFaith.GetName|V] bekehrt werden"

  action_convert_vassals: "[recipient.GetShortUINameNoTooltip] kann bekehrt werden"
  action_convert_vassals_label: "$action_convert_vassals$"
  action_convert_vassals_desc: "Dein [actor.Custom2('RelationToMe', recipient)] [recipient.GetShortUIName] kann zu [actor.GetFaith.GetName|V] bekehrt werden"
  action_convert_vassals_click: "#I Klicken, um Bekehrung zu verlangen#!"
  action_convert_vassals_combined_label: "[recipient.GetRelationToString( GetPlayer )], [recipient.GetShortUINameNoTooltip]"
  action_convert_vassals_combined_group_name: "Eure Höflinge können konvertiert werden"
  action_convert_vassals_combined_group_label: "$action_convert_vassals_combined_group_name$"
  action_convert_vassals_combined_group_description: "Mehrere Eurer Höflinge können zu [actor.GetFaith.GetName|V] konvertiert werden"

  alertmanager_title_invitations: "Einladungen"
  alertmanager_title_education: "Bildung"
  alertmanager_title_marriage: "Heirat"
  alertmanager_title_give_lands: "Titel vergeben"
  alertmanager_title_convert: "Bekehrung"
  alertmanager_title_witchcraft: "Hexerei"

  alertmanager_VIEW_TITLE: "Alert Managers"
  alertmanager_button_tt: "#T Anzeigen des Alert Managers"

  alertmanager_widget_invitations: "Aktivieren Sie Einladungsbenachrichtigungen"
  alertmanager_widget_invitations_tooltip: ""
  alertmanager_widget_invitationsdynasty: "$alertmanager_widget_marriagedynasty$"
  alertmanager_widget_invitationsdynasty_tooltip: ""
  alertmanager_widget_hook: "Und auch für Mitglieder, die mit einem [Hook|E] eingeladen werden können"
  alertmanager_widget_hook_tooltip: ""
  alertmanager_widget_education: "Aktivieren Sie Bildungswarnungen"
  alertmanager_widget_education_tooltip: ""
  alertmanager_widget_educationdynasty: "$alertmanager_widget_marriagedynasty$"
  alertmanager_widget_educationdynasty_tooltip: ""
  alertmanager_widget_gardian: "[guardians|E] zuweisen"
  alertmanager_widget_gardian_tooltip: ""
  alertmanager_widget_focus: "Um den [education_focus|E] zu ändern"
  alertmanager_widget_focus_tooltip: ""
  alertmanager_widget_marriage: "Aktivieren Sie [marriage|E]-Benachrichtigungen"
  alertmanager_widget_marriage_tooltip: ""
  alertmanager_widget_marriagedynasty: "Für Mitglieder Ihrer [dynasty|E]"
  alertmanager_widget_marriagedynasty_tooltip: ""
  alertmanager_widget_marriagechild: "Für die [children|E]"
  alertmanager_widget_marriagechild_tooltip: ""
  alertmanager_widget_marriageadult: "Für [adults|E]"
  alertmanager_widget_marriageadult_tooltip: ""
  alertmanager_widget_marriagecourtier: "Für Mitglieder Ihres [court|E]"
  alertmanager_widget_marriagecourtier_tooltip: ""
  alertmanager_widget_marriagecourtier_unworthy: "Nur [courtiers|E] mit Merkmalen [congenital|E]"
  alertmanager_widget_marriagecourtier_unworthy_tooltip: ""
  alertmanager_widget_marriagecourtier_infertile: "Unfruchtbare Höflinge ignorieren"
  alertmanager_widget_marriagecourtier_infertile_tooltip: ""
  alertmanager_widget_give_lands: "Aktivieren Sie Benachrichtigungen, um Mitgliedern Ihrer [dynasty|E] [titles|E] zu verleihen"
  alertmanager_widget_give_lands_tooltip: ""
  alertmanager_widget_convert: "Aktivieren Sie Conversion-Benachrichtigungen"
  alertmanager_widget_convert_tooltip: ""
  alertmanager_widget_convert_courtier: "$alertmanager_widget_marriagecourtier$"
  alertmanager_widget_convert_courtier_tooltip: ""
  alertmanager_widget_convert_vassal: "Für deine [vassals|E]"
  alertmanager_widget_convert_vassal_tooltip: ""
  alertmanager_widget_convert_subvassal: "Ignoriere indirekte Vasallen"
  alertmanager_widget_convert_subvassal_tooltip: ""
  alertmanager_widget_convert_baron: "Ignoriere [barons|E] & Bürgermeister"
  alertmanager_widget_convert_baron_tooltip: ""
  alertmanager_widget_witchcraft: "Aktivieren Sie Warnungen, um Ihre [dynasty|E] davon zu überzeugen, den Gehörnten Gott anzubeten."
  alertmanager_widget_witchcraft_tooltip: ""
  